class Player(): 
    """Represents the player of a grid based game. """

    def __init__(self, pos_x, pos_y, grid):
        """Constructor: Creates player with supplied values. """

        self.pos_x = pos_x
        self.pos_y = pos_y

        self.move_counter = 0
        #self.next_valid = False
        self.mistakes_counter = 0

        self.grid = grid


    def move(self, direction):
        """Moves the player in some direction. Called by event handler."""

        if direction == "up":
            if self.pos_y > 0:
                if self.is_valid(-1, 0):
                    self.pos_y -= 1
                    self.move_counter += 1
            else:
                print("Player at top, cannot move up")

        elif direction == "down":
            if self.pos_y < self.grid.cols:
                if self.is_valid(1, 0):
                    self.pos_y += 1
                    self.move_counter += 1
            else:
                print("Player at bottom, cannot move down")

        elif direction == "left":
            if self.pos_x > 0:
                if self.is_valid(0, -1):
                    self.pos_x -= 1
                    self.move_counter += 1
            else:
                print("Player at left edge, cannot move left")

        elif direction == "right":
            if self.pos_x < self.grid.rows:
                if self.is_valid(0, 1):
                    self.pos_x += 1
                    self.move_counter += 1
            else:
                print("Player at right edge, cannot move right")

        else:
            print("Invalid Move Command. Try again.")

    def is_valid(self, y_dif, x_dif):
        """Checks if a move is valid by matching it to the path generated by the grid"""

        """
        ---DEBUG PRINTS---
        print("Current space in path:")
        print(self.path[self.move_counter + 0])

        print("Next space in path:")
        print(self.path[self.move_counter + 1])

        print("Player moving to:")
        print(str("(" + str(self.pos_y + y_dif) + ", " + str(self.pos_x + x_dif) + ")"))
        """

        #Compares grid coordinates.
        #This compares the string output by the tuple to the string produced by the movement.
        #If they match, allow the move. 

        new_x = self.pos_x + x_dif
        new_y = self.pos_y + y_dif
        new_pos = (self.pos_y + y_dif, self.pos_x + x_dif)
        cur_tile = self.grid.get_tile(self.pos_y, self.pos_x)
        new_tile = self.grid.get_tile(new_y, new_x)
        valid_next = self.grid.pattern.apply_pattern(cur_tile)
        valid_prev = self.grid.pattern.get_prev(cur_tile)

        if new_tile in (valid_next, valid_prev): 
            print("Correct Move")
            return True
        else:
            self.mistakes_counter += 1
            return False

